config/routes.rb
WikiPractice::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :articles, only: [:show, :index]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About the project</h1>
<p>This project will allow academics to rate the quality of Wikipedia articles</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<h1>Contact us</h1>
<p>Fill in contact info here</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="center hero-unit">
    <h1>Wiki Practice</h1>

    <h2>A practice app for rating Wikipedia pages</h2>

    <%= link_to "Add a review", new_review_path, class: "btn btn-large btn-primary" %>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Wiki Practice</h1>

    <h2>A practice app for rating Wikipedia pages</h2>

    <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>