config/routes.rb
WikiPractice::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :articles, only: [:show, :index]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/article.rb
class Article < ActiveRecord::Base
  # I think the below has_many is correct but not sure.  It seems to work ok, but not sure the syntax is right.
  has_many :reviews, primary_key: :page_id, foreign_key: "page_id"
  validates :page_id, presence: true, uniqueness: true
  validates :title, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
    @reviews = @article.reviews.order(created_at: :desc)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<% provide(:title, 'Reviewed Wikipedia Articles') %>
<h1>Reviewed Wikipedia Articles</h1>

<ul class="users">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

app/views/articles/show.html.erb
<% provide(:title, "All Reviews for #{@article.title}") %>
<h1>All Reviews for <%= @article.title %></h1>

<ul class="users">
  <% @reviews.each do |review| %>
    <li>
    <%= link_to review.title, review_path(review) %>
    Reviewed by: <%= review.user.name %>
    </li>
  <% end %>
</ul>